package config

import "fmt"

var (
	// Following values will be set during build.
	// Do NOT manually modify them.

	// ProductVersion is current product version.
	ProductVersion = "Not provided"
	// GitSHA is Git Commit Hash
	GitSHA = "Not provided"
	// GitBranch is Git branch name
	GitBranch = "Not provided"
	// GoVersion is go compiler version `go version`
	GoVersion = "Not provided"
	// BuildVersion is generated by `git describe --always --long --dirty`
	BuildVersion = "Not provided"
	// BuildTime is go build time
	BuildTime = "Not provided"
)

// NewVersionMetadata 返回版本信息的元数据
func NewVersionMetadata() map[string]string {
	return map[string]string{
		"ProductVersion": ProductVersion,
		"GitSHA":         GitSHA,
		"GitBranch":      GitBranch,
		"GoVersion":      GoVersion,
		"BuildVersion":   BuildVersion,
		"BuildTime":      BuildTime,
	}
}

// PrintFullVersionInfo 打印版本信息
func PrintFullVersionInfo() {
	fmt.Println(ProductVersion)
	fmt.Println("BuildVersion:", BuildVersion)
	fmt.Println("BuildTime:", BuildTime)
	fmt.Println("GitSHA:", GitSHA)
	fmt.Println("GitBranch:", GitBranch)
	fmt.Println(GoVersion)
}
