package handler

import (
	"fmt"
)

const (
	// ErrDatabase 数据库错误
	ErrDatabase = 10001
	// ErrClientUnauthorized 未授权
	ErrClientUnauthorized = 1000
	// ErrUserUnauthorized 未授权
	ErrUserUnauthorized = 1100
	// ErrUsernamePasswordNotMatch 用户名密码错误
	ErrUsernamePasswordNotMatch = 1200
	// ErrNullClientID 空的客户端ID
	ErrNullClientID = 1300
	// ErrIncorrectClientID 客户端ID不正确
	ErrIncorrectClientID = 1400
	// ErrInvalidSecretKey secretkey错误
	ErrInvalidSecretKey = 1500
	// ErrInvalidUser 无效的用户
	ErrInvalidUser = 1600
	// ErrPhonePasswordNotMatch 电话密码不匹配
	ErrPhonePasswordNotMatch = 1700
	// ErrExistPassword 密码已经存在
	ErrExistPassword = 1800
	// ErrIncorrectPassword 密码不正确
	ErrIncorrectPassword = 1900
	// ErrExistRegisteredPhone 注册手机号已经存在
	ErrExistRegisteredPhone = 2000
	// ErrInValidMVC 验证码失效
	ErrInValidMVC = 2100
	// ErrGetAccessTokenFailure 失败去得到Access-Token
	ErrGetAccessTokenFailure = 2200
	// ErrDeactivatedUser 用户被禁用
	ErrDeactivatedUser = 2700
	// ErrInvalidValidationValue 非法的验证方式的值
	ErrInvalidValidationValue = 10000
	// ErrInvalidSecureQuestionValidationMethod 非法的安全问题验证方法
	ErrInvalidSecureQuestionValidationMethod = 11000
	// ErrWrongSecureQuestionCount 安全问题数量不匹配
	ErrWrongSecureQuestionCount = 12000
	// ErrSecureQuestionExist 已经设置过密保
	ErrSecureQuestionExist = 13000
	// ErrEmptySecureQuestion 密保问题为空
	ErrEmptySecureQuestion = 14000
	// ErrEmptyAnswer  答案为空
	ErrEmptyAnswer = 15000
	// ErrSamePassword  新密码与旧密码相同
	ErrSamePassword = 16000
	// ErrMismatchQuestion 传入的密保问题错误
	ErrMismatchQuestion = 17000
	// ErrWrongFormatQuestion 传入的密保问题格式错误
	ErrWrongFormatQuestion = 18000
	// ErrRepeatedQuestion 问题重复
	ErrRepeatedQuestion = 19000
	// ErrWrongFormatPhone 手机号格式错误
	ErrWrongFormatPhone = 20000
	// ErrNonexistentUsername 用户名不存在
	ErrNonexistentUsername = 21000
	// ErrNoneExistentPhone 手机号不存在
	ErrNoneExistentPhone = 22000
	// ErrInvalidEmailAddress 邮箱格式错误
	ErrInvalidEmailAddress = 23000
	// ErrSecureEmailExists 用户已经设置了自己的邮箱
	ErrSecureEmailExists = 24000
	// ErrSecureEmailUsedByOthers 邮箱已经被其他人设置
	ErrSecureEmailUsedByOthers = 25000
	// ErrSecureEmailNotSet 没有设置邮箱
	ErrSecureEmailNotSet = 26000
	// ErrSecureEmailAddressNotMatched 与原邮箱不匹配
	ErrSecureEmailAddressNotMatched = 27000
	// ErrInvalidEmailNotificationAction 非法的邮件通知的操作
	ErrInvalidEmailNotificationAction = 28000
	// ErrUsedVcRecord 该记录已经被使用过
	ErrUsedVcRecord = 29000
	// ErrExpiredVcRecord 该记录已经过期
	ErrExpiredVcRecord = 30000
	// ErrInvalidVcRecord 验证码错误
	ErrInvalidVcRecord = 31000
	// ErrInvalidRequestCountIn1Minute 1分钟请求次数非法
	ErrInvalidRequestCountIn1Minute = 32000
	// ErrExsitRegion 区域已经存在
	ErrExsitRegion = 33000
	// ErrExsitSignInPhone 登录电话已经存在
	ErrExsitSignInPhone = 34000
	// ErrInvalidSigninPhone 无效的登录电话
	ErrInvalidSigninPhone = 35000
	// ErrInvalidVerificationNumber 无效的VerificationNumber
	ErrInvalidVerificationNumber = 36000
	// ErrNotExistSigninPhone 登录手机号不存在
	ErrNotExistSigninPhone = 37000
	// ErrSamePhone 新旧手机号一样
	ErrSamePhone = 38000
	// ErrWrongSendVia 发送验证码的方式错误
	ErrWrongSendVia = 39000
	// ErrInvalidSendValue 发送验证码的方式的值错误
	ErrInvalidSendValue = 40000
	// ErrInvalidSigninEmail 无效的安全邮箱
	ErrInvalidSigninEmail = 41000
	// ErrInvalidValidationType 验证邮箱验证码时非法的验证类型
	ErrInvalidValidationType = 42000
	// ErrInvalidValidationMethod 获取方式非法
	ErrInvalidValidationMethod = 43000
	// ErrNotExistNewSecureEmail 新安全邮箱不存在
	ErrNotExistNewSecureEmail = 45000
	// ErrSameEmail 新旧安全邮箱相同
	ErrSameEmail = 46000
	// ErrSameSecureQuestion 新旧密保问题一样
	ErrSameSecureQuestion = 47000
	// ErrNotExistOldPassword 旧密码不存在
	ErrNotExistOldPassword = 48000
	// ErrCurrentSecureQuestionsNotSet 当前用户的密保问题未设置
	ErrCurrentSecureQuestionsNotSet = 49000
	// ErrNoneExistSecureEmail 邮箱不存在
	ErrNoneExistSecureEmail = 50000
	// ErrSignInPhoneNotBelongsToUser 手机号不属于用户
	ErrSignInPhoneNotBelongsToUser = 53000
	// ErrNonexistentPassword 密码不存在
	ErrNonexistentPassword = 55000
	// ErrIncorrectOldPassword 旧密码不正确
	ErrIncorrectOldPassword = 56000
	// ErrWrongFormatOfNickname 昵称格式错误
	ErrWrongFormatOfNickname = 57000
	// ErrSensitiveWordsInNickname 昵称包含敏感词
	ErrSensitiveWordsInNickname = 58000
	// ErrReservedWordsInNickname 昵称包含保留词
	ErrReservedWordsInNickname = 59000
	// ErrMaskWordsInNickname 昵称包含屏蔽词
	ErrMaskWordsInNickname = 60000
	// ErrEmptyNickname 昵称为空
	ErrEmptyNickname = 61000
	// ErrEmptyGender 性别为空
	ErrEmptyGender = 62000
	// ErrEmptyBirthday 生日为空
	ErrEmptyBirthday = 63000
	// ErrEmptyHeight 身高为空
	ErrEmptyHeight = 64000
	// ErrEmptyWeight 体重为空
	ErrEmptyWeight = 65000
	// ErrEmptyLanguage 语言为空
	ErrEmptyLanguage = 66000
	// ErrEmptyRegion 区域为空
	ErrEmptyRegion = 67000
	// ErrWrongFormatOfPassword 密码格式错误
	ErrWrongFormatOfPassword = 68000
	// ErrEmptyPassword 密码为空
	ErrEmptyPassword = 69000
	// ErrNotEmailOfCurrentUser 非当前绑定邮箱
	ErrNotEmailOfCurrentUser = 70000
	// ErrNoneExistUser 不存在的User
	ErrNoneExistUser = 71000
	// ErrSendMoreSMSInOneMinute 一分钟内的发送多条
	ErrSendMoreSMSInOneMinute = 72000
	// ErrSendSMS 短信发送异常
	ErrSendSMS = 74000
	// ErrSendEmail 邮件发送异常
	ErrSendEmail = 75000
	// ErrInvalidGender 非法的性别
	ErrInvalidGender = 76000
	// ErrInvalidRegion 非法的区域
	ErrInvalidRegion = 77000
	// ErrInvalidVerificationType 非法的验证方式
	ErrInvalidVerificationType = 78000
	// ErrInvalidSmsTemplateAction 短信发送模版错误
	ErrInvalidSmsTemplateAction = 79000
	// ErrInvalidLanguage 语言错误
	ErrInvalidLanguage = 80000
	// ErrSignPhoneNotSet 登陆手机号码未设置
	ErrSignPhoneNotSet = 81000
	// ErrGenRandomString 生成随机字符串失败
	ErrGenRandomString = 82000
)

// NewError 构建一个新的 Error
func NewError(code int, err error) error {
	return fmt.Errorf("[errcode:%d] %s", code, err.Error())
}

// NewErrorCause 构建一个error
func NewErrorCause(code int, err error, cause string) error {
	return NewError(code, err)
}
