-- 修改表的编码格式为utf8mb4
alter table `account_l_record` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `audit_user_credential_update` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `audit_user_signin_signout` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `client` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `device` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `device_organization_binding` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `feedback` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `jinmu_account_preferences` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `jinmu_company` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `jinmu_contract` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `jinmu_feedback` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `jinmu_l_access_token` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `jinmu_l_account` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `jinmu_log` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `jinmu_mac` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `jinmu_product` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `jinmu_record` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `jinmu_status` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `jinmu_subject` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `jinmu_token` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `legacy_jinmu_account_preferences` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `legacy_jinmu_company` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `legacy_jinmu_contract` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `legacy_jinmu_feedback` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `legacy_jinmu_log` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `legacy_jinmu_mac` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `legacy_jinmu_product` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `legacy_jinmu_record` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `legacy_jinmu_status` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `legacy_jinmu_subject` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `legacy_jinmu_token` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `legacy_organization_admin` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `legacy_subscription` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `legacy_user` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `local_notifications` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `notification_preferences` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `organization` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `organization_owner` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `organization_user` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `phone_or_email_verfication` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `pn_record` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `push_notification` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `record` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `scanned_qrcode_record` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `sem_record` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `sms_record` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `subscription` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `subscription_activation_code` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `subscription_renew_record` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `subscription_transfer_record` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `temp_record` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `temp_user_profile` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `transaction_number` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `user` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `user_access_token` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `user_preferences` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `user_profile` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `user_subscription_sharing` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `user_used_device` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `verification_code` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `wechat_h5_session` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `wechat_user` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;
alter table `wxmp_tmp_qrcode` character set utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- 修改表的字段编码格式为utf8mb4
ALTER TABLE `account_l_record` MODIFY `account` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '账户';
ALTER TABLE `audit_user_credential_update` MODIFY `client_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '客户端ID';
ALTER TABLE `audit_user_credential_update` MODIFY `updated_record_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '更新记录的类型,username,phone,email,password';
ALTER TABLE `audit_user_credential_update` MODIFY `old_value` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '旧的数值';
ALTER TABLE `audit_user_credential_update` MODIFY `new_value` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '新的数值';
ALTER TABLE `audit_user_signin_signout` MODIFY `client_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '客户端ID';
ALTER TABLE `audit_user_signin_signout` MODIFY `ip` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ip地址';
ALTER TABLE `audit_user_signin_signout` MODIFY `extra_params` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '登录/登出参数';
ALTER TABLE `audit_user_signin_signout` MODIFY `record_type` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '登录或登出记录的类型,signin,signout';
ALTER TABLE `audit_user_signin_signout` MODIFY `sign_in_machine` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '登录机器';
ALTER TABLE `client` MODIFY `client_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '客户端ID';
ALTER TABLE `client` MODIFY `secret_key` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '客户端授权密钥';
ALTER TABLE `client` MODIFY `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '客户端名称';
ALTER TABLE `client` MODIFY `zone` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '客户端所在区域';
ALTER TABLE `client` MODIFY `customized_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '定制化代码';
ALTER TABLE `client` MODIFY `remark` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '客户端所备注';
ALTER TABLE `client` MODIFY `usage` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用途';
ALTER TABLE `device` MODIFY `sn` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'SN号';
ALTER TABLE `device` MODIFY `pin` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '验证码';
ALTER TABLE `device` MODIFY `zone` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '设备所在区域';
ALTER TABLE `device` MODIFY `model` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '设备型号';
ALTER TABLE `device` MODIFY `customized_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '定制化代码';
ALTER TABLE `device` MODIFY `tags` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '标签列表';
ALTER TABLE `device` MODIFY `remarks` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '备注';
ALTER TABLE `feedback` MODIFY `content` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '反馈内容';
ALTER TABLE `feedback` MODIFY `contact_way` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '联系方式';
ALTER TABLE `jinmu_l_access_token` MODIFY `account` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '账户';
ALTER TABLE `jinmu_l_access_token` MODIFY `token` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '当前会话的令牌';
ALTER TABLE `jinmu_l_access_token` MODIFY `machine_uuid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '机器的标识';
ALTER TABLE `jinmu_l_account` MODIFY `account` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '账户';
ALTER TABLE `jinmu_l_account` MODIFY `password` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户登录密码';
ALTER TABLE `jinmu_l_account` MODIFY `remark` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '账户备注';
ALTER TABLE `legacy_jinmu_account_preferences` MODIFY `account` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '产品账号';
ALTER TABLE `legacy_jinmu_company` MODIFY `company_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '公司统编';
ALTER TABLE `legacy_jinmu_company` MODIFY `account` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '产品账号';
ALTER TABLE `legacy_jinmu_company` MODIFY `company_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '公司名称';
ALTER TABLE `legacy_jinmu_company` MODIFY `company_address` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '公司地址';
ALTER TABLE `legacy_jinmu_company` MODIFY `company_phone` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '公司移动电话';
ALTER TABLE `legacy_jinmu_company` MODIFY `company_line` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '公司固定电话';
ALTER TABLE `legacy_jinmu_company` MODIFY `company_email` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '公司联系邮箱';
ALTER TABLE `legacy_jinmu_company` MODIFY `company_state` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '公司所在省份';
ALTER TABLE `legacy_jinmu_company` MODIFY `company_city` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '公司所在城市';
ALTER TABLE `legacy_jinmu_company` MODIFY `company_block` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '公司所在区域';
ALTER TABLE `legacy_jinmu_company` MODIFY `legal_person` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '公司法人';
ALTER TABLE `legacy_jinmu_company` MODIFY `company_representative` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '公司联系人';
ALTER TABLE `legacy_jinmu_company` MODIFY `company_bank_account` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '公司银行账号';
ALTER TABLE `legacy_jinmu_company` MODIFY `company_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '公司类型';
ALTER TABLE `legacy_jinmu_contract` MODIFY `contract_code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '合同编号';
ALTER TABLE `legacy_jinmu_contract` MODIFY `account` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '产品账号';
ALTER TABLE `legacy_jinmu_contract` MODIFY `monetary_unit` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '合同金额单位';
ALTER TABLE `legacy_jinmu_contract` MODIFY `contract_content` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '合同内容';
ALTER TABLE `legacy_jinmu_contract` MODIFY `contract_type` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '合同类型T|F';
ALTER TABLE `legacy_jinmu_contract` MODIFY `buyer_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '购买产品公司';
ALTER TABLE `legacy_jinmu_contract` MODIFY `seller_code` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '销售产品公司';
ALTER TABLE `legacy_jinmu_feedback` MODIFY `account` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '产品账号';
ALTER TABLE `legacy_jinmu_feedback` MODIFY `contact_way` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '联系方式';
ALTER TABLE `legacy_jinmu_log` MODIFY `log_key` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'Log唯一key';
ALTER TABLE `legacy_jinmu_log` MODIFY `request_uri` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '請求的UTL';
ALTER TABLE `legacy_jinmu_log` MODIFY `server_addr` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '服務器IP地址';
ALTER TABLE `legacy_jinmu_log` MODIFY `remote_addr` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '客戶端IP地址';
ALTER TABLE `legacy_jinmu_log` MODIFY `request_method` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '網絡請求方法';
ALTER TABLE `legacy_jinmu_log` MODIFY `info_lang` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'LANG資訊';
ALTER TABLE `legacy_jinmu_log` MODIFY `info_route` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '伺服器內路由資訊';
ALTER TABLE `legacy_jinmu_log` MODIFY `response_description` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '';
ALTER TABLE `legacy_jinmu_log` MODIFY `memory_use` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '內存使用情況';
ALTER TABLE `legacy_jinmu_mac` MODIFY `mac` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '仪器MAC';
ALTER TABLE `legacy_jinmu_product` MODIFY `account` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '产品账号';
ALTER TABLE `legacy_jinmu_product` MODIFY `password` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '账号密码';
ALTER TABLE `legacy_jinmu_product` MODIFY `pad_app_version_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'APP 版本名称';
ALTER TABLE `legacy_jinmu_product` MODIFY `pad_app_version_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'APP 版本代码';
ALTER TABLE `legacy_jinmu_product` MODIFY `pad_app_downloadurl` varchar(320) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'APP 下载地址';
ALTER TABLE `legacy_jinmu_product` MODIFY `pad_mac_address` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '平板MAC';
ALTER TABLE `legacy_jinmu_product` MODIFY `pad_device_code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '平板编码';
ALTER TABLE `legacy_jinmu_product` MODIFY `appratus_model` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '仪器型号';
ALTER TABLE `legacy_jinmu_product` MODIFY `appratus_mac_address` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '仪器MAC';
ALTER TABLE `legacy_jinmu_product` MODIFY `appratus_device_code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '仪器编码';
ALTER TABLE `legacy_jinmu_product` MODIFY `account_type` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  DEFAULT 'normal' COMMENT '区分项目与普通账号';
ALTER TABLE `legacy_jinmu_subject` MODIFY `account` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '产品账号';
ALTER TABLE `legacy_jinmu_subject` MODIFY `pin` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '身份证号码';
ALTER TABLE `legacy_jinmu_subject` MODIFY `name` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '姓名';
ALTER TABLE `legacy_jinmu_subject` MODIFY `nickname` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '账号昵称';
ALTER TABLE `legacy_jinmu_subject` MODIFY `gender` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '性别M|F';
ALTER TABLE `legacy_jinmu_subject` MODIFY `phone` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '电话';
ALTER TABLE `legacy_jinmu_subject` MODIFY `email` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '邮箱';
ALTER TABLE `legacy_jinmu_subject` MODIFY `nationality` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '国籍或地区';
ALTER TABLE `legacy_jinmu_subject` MODIFY `state` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '所在省份';
ALTER TABLE `legacy_jinmu_subject` MODIFY `city` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '所在城市';
ALTER TABLE `legacy_jinmu_subject` MODIFY `block` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '所在区域';
ALTER TABLE `legacy_jinmu_subject` MODIFY `remark` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '用户备注';
ALTER TABLE `legacy_jinmu_subject` MODIFY `customized_code` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '自定义编码';
ALTER TABLE `legacy_jinmu_token` MODIFY `account_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '';
ALTER TABLE `legacy_jinmu_token` MODIFY `token` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '';
ALTER TABLE `legacy_subscription` MODIFY `customized_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '自定义代码';
ALTER TABLE `legacy_user` MODIFY `username` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户名';
ALTER TABLE `legacy_user` MODIFY `password` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户登录密码';
ALTER TABLE `legacy_user` MODIFY `zone` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户选择的区域';
ALTER TABLE `legacy_user` MODIFY `register_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户注册方式';
ALTER TABLE `legacy_user` MODIFY `register_source_client_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '发起注册的客户端ID';
ALTER TABLE `legacy_user` MODIFY `customized_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '定制化代码';
ALTER TABLE `legacy_user` MODIFY `nickname` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户昵称';
ALTER TABLE `legacy_user` MODIFY `phone` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户电话号码';
ALTER TABLE `legacy_user` MODIFY `email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户联系邮箱';
ALTER TABLE `legacy_user` MODIFY `country` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '国家';
ALTER TABLE `legacy_user` MODIFY `state` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户所在省份';
ALTER TABLE `legacy_user` MODIFY `city` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户所在城市';
ALTER TABLE `legacy_user` MODIFY `district` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '地区';
ALTER TABLE `legacy_user` MODIFY `street` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户所在街道';
ALTER TABLE `legacy_user` MODIFY `user_defined_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '用户自定义代码';
ALTER TABLE `legacy_user` MODIFY `remark` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户备注';
ALTER TABLE `local_notifications` MODIFY `title` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '推送标题';
ALTER TABLE `local_notifications` MODIFY `content` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '推送内容';
ALTER TABLE `local_notifications` MODIFY `timezone` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '时区信息';
ALTER TABLE `local_notifications` MODIFY `frequency` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '推送时间间隔基本单位,FrequencyDaily,FrequencyWeekly,FrequencyMonthly';
ALTER TABLE `local_notifications` MODIFY `weekdays` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '一周内有哪些天推送,这里保存的是json类型';
ALTER TABLE `local_notifications` MODIFY `month_days` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '一个月内有哪些天推送,这里保存的是json类型';
ALTER TABLE `organization` MODIFY `legacy_account` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Legacy的acount信息';
ALTER TABLE `organization` MODIFY `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '组织名称';
ALTER TABLE `organization` MODIFY `phone` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '联系电话';
ALTER TABLE `organization` MODIFY `email` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '联系Email';
ALTER TABLE `organization` MODIFY `contact` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '联系人';
ALTER TABLE `organization` MODIFY `type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '组织机构类型';
ALTER TABLE `organization` MODIFY `country` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '组织机构所在国家';
ALTER TABLE `organization` MODIFY `state` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '组织所在省份';
ALTER TABLE `organization` MODIFY `city` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '组织所在城市';
ALTER TABLE `organization` MODIFY `district` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '组织所在区';
ALTER TABLE `organization` MODIFY `street` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '组织所在街道';
ALTER TABLE `organization` MODIFY `address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '组织地址';
ALTER TABLE `organization` MODIFY `postal_code` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '邮政编码';
ALTER TABLE `organization` MODIFY `remark` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '备注信息';
ALTER TABLE `organization` MODIFY `customized_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '定制化代码 例如 custom_sanshui custom_dengyun';
ALTER TABLE `phone_or_email_verfication` MODIFY `verification_type` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '发送方式,phone,email';
ALTER TABLE `phone_or_email_verfication` MODIFY `verification_number` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '验证号';
ALTER TABLE `phone_or_email_verfication` MODIFY `send_to` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '接收人';
ALTER TABLE `phone_or_email_verfication` MODIFY `nation_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '国家代码';
ALTER TABLE `push_notification` MODIFY `pn_display_time` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '消息上的显示的时间';
ALTER TABLE `push_notification` MODIFY `pn_title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '消息的标题';
ALTER TABLE `push_notification` MODIFY `pn_image_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '消息图片的URL';
ALTER TABLE `push_notification` MODIFY `pn_content_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '消息内容的URL';
ALTER TABLE `record` MODIFY `client_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '客户端ID';
ALTER TABLE `record` MODIFY `remark` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '备注';
ALTER TABLE `record` MODIFY `sys_remark` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '系统备注';
ALTER TABLE `record` MODIFY `answers` varchar(4000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '智能分析的回答，JSON格式';
ALTER TABLE `record` MODIFY `record_token` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '';
ALTER TABLE `record` MODIFY `transaction_number` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '流水号';
ALTER TABLE `record` MODIFY `s3_key` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 's3的key';
ALTER TABLE `record` MODIFY `stress_state` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'json格式的应激态状态，格式map[string]bool';
ALTER TABLE `record` MODIFY `analyze_body` varchar(8000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '新分析接口的body';
ALTER TABLE `sem_record` MODIFY `to_address` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '收件邮箱地址';
ALTER TABLE `sem_record` MODIFY `template_action` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '模版行为';
ALTER TABLE `sem_record` MODIFY `template_param` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '模版参数';
ALTER TABLE `sem_record` MODIFY `sem_error_log` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '邮箱错误信息';
ALTER TABLE `sms_record` MODIFY `phone` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '联系电话';
ALTER TABLE `sms_record` MODIFY `template_action` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '模版行为';
ALTER TABLE `sms_record` MODIFY `nation_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '国家代码';
ALTER TABLE `sms_record` MODIFY `template_param` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '模版参数';
ALTER TABLE `sms_record` MODIFY `sms_error_log` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '短信错误信息';
ALTER TABLE `sms_record` MODIFY `serial_number` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '序列号';
ALTER TABLE `subscription` MODIFY `customized_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '自定义代码';
ALTER TABLE `subscription_activation_code` MODIFY `code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '激活码';
ALTER TABLE `subscription_activation_code` MODIFY `checksum` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '校验位';
ALTER TABLE `subscription_activation_code` MODIFY `activation_lock` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '锁';
ALTER TABLE `subscription_activation_code` MODIFY `batch` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '批次';
ALTER TABLE `subscription_renew_record` MODIFY `client_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '客户端ID';
ALTER TABLE `subscription_transfer_record` MODIFY `client_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '客户端ID';
ALTER TABLE `temp_record` MODIFY `stress_state` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'json格式的应激态状态，格式map[string]bool';
ALTER TABLE `temp_record` MODIFY `analyze_body` varchar(8000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '新分析接口的body';
ALTER TABLE `temp_user_profile` MODIFY `nickname_initial` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '昵称首字母';
ALTER TABLE `user` MODIFY `register_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户注册方式';
ALTER TABLE `user` MODIFY `zone` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户选择的区域';
ALTER TABLE `user` MODIFY `customized_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '定制化代码';
ALTER TABLE `user` MODIFY `user_defined_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '用户自定义代码';
ALTER TABLE `user` MODIFY `remark` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户备注';
ALTER TABLE `user` MODIFY `encrypted_password` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户encrypt后的登录密码';
ALTER TABLE `user` MODIFY `seed` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '随机种子';
ALTER TABLE `user` MODIFY `secure_email` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '安全邮箱';
ALTER TABLE `user` MODIFY `signin_phone` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '登录Phone';
ALTER TABLE `user` MODIFY `signin_username` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '登录用户名';
ALTER TABLE `user` MODIFY `nation_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '国家代码';
ALTER TABLE `user` MODIFY `language` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'zh-Hans' COMMENT '语言';
ALTER TABLE `user` MODIFY `register_source` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户来源';
ALTER TABLE `user` MODIFY `secure_question_1` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '密保问题1';
ALTER TABLE `user` MODIFY `secure_question_2` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '密保问题2';
ALTER TABLE `user` MODIFY `secure_question_3` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '密保问题3';
ALTER TABLE `user` MODIFY `secure_answer_1` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '密保答案1';
ALTER TABLE `user` MODIFY `secure_answer_2` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '密保答案2';
ALTER TABLE `user` MODIFY `secure_answer_3` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '密保答案3';
ALTER TABLE `user` MODIFY `region` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'mainland_china' COMMENT '区域';
ALTER TABLE `user` MODIFY `sys_remark` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '系统备注';
ALTER TABLE `user_access_token` MODIFY `token` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '当前会话的令牌';
ALTER TABLE `user_profile` MODIFY `nickname` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户昵称';
ALTER TABLE `user_profile` MODIFY `nickname_initial` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '昵称首字母';
ALTER TABLE `user_profile` MODIFY `gender` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '用户性别 M 男 F 女';
ALTER TABLE `user_used_device` MODIFY `client_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '客户端ID';
ALTER TABLE `verification_code` MODIFY `usage` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '使用用途';
ALTER TABLE `verification_code` MODIFY `sn` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '序列号';
ALTER TABLE `verification_code` MODIFY `code` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '验证码';
ALTER TABLE `verification_code` MODIFY `send_via` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '发送方式,phone,email';
ALTER TABLE `verification_code` MODIFY `nation_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '国家代码';
ALTER TABLE `verification_code` MODIFY `send_to` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '接收人';
ALTER TABLE `wechat_h5_session` MODIFY `session_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Session ID';
ALTER TABLE `wechat_h5_session` MODIFY `state` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '微信 OAuth 验证的 state';
ALTER TABLE `wechat_h5_session` MODIFY `open_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '微信OpenID';
ALTER TABLE `wechat_h5_session` MODIFY `union_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '微信UnionID';
ALTER TABLE `wechat_user` MODIFY `open_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '微信OpenID';
ALTER TABLE `wechat_user` MODIFY `union_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '微信UnionID';
ALTER TABLE `wechat_user` MODIFY `origin_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '公众号原始ID';
ALTER TABLE `wechat_user` MODIFY `nickname` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户昵称';
ALTER TABLE `wechat_user` MODIFY `avatar_image_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '头像图片URL';
ALTER TABLE `wxmp_tmp_qrcode` MODIFY `raw_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '二维码原始URL';
ALTER TABLE `wxmp_tmp_qrcode` MODIFY `ticket` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '二维码的ticket';
ALTER TABLE `wxmp_tmp_qrcode` MODIFY `account` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '账户';
ALTER TABLE `wxmp_tmp_qrcode` MODIFY `machine_uuid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '机器的标识';
ALTER TABLE `wxmp_tmp_qrcode` MODIFY `origin_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '公众号原始ID';
